name: RPA Agenda RMB - Execução Diária

on:
  schedule:
    - cron: "0 10 * * *"  # 07:00 BRT (UTC-3) = 10:00 UTC
  workflow_dispatch:  # permite rodar manualmente também

jobs:
  rpa-execution:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libasound2-dev

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Create environment file
        run: |
          echo "SUPABASE_HOST=${{ secrets.SUPABASE_HOST }}" >> config.env
          echo "SUPABASE_PORT=${{ secrets.SUPABASE_PORT }}" >> config.env
          echo "SUPABASE_DATABASE=${{ secrets.SUPABASE_DATABASE }}" >> config.env
          echo "SUPABASE_USER=${{ secrets.SUPABASE_USER }}" >> config.env
          echo "SUPABASE_PASSWORD=${{ secrets.SUPABASE_PASSWORD }}" >> config.env
          echo "SUPABASE_TABLE_NAME=${{ secrets.SUPABASE_TABLE_NAME }}" >> config.env
          echo "NOVAJUS_USERNAME=${{ secrets.NOVAJUS_USERNAME }}" >> config.env
          echo "NOVAJUS_PASSWORD=${{ secrets.NOVAJUS_PASSWORD }}" >> config.env

      - name: Run RPA Script
        id: rpa
        run: |
          echo "Starting RPA script..."
          python rpa_agenda_rmb.py 2>&1 | tee rpa_output.log
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Show logs on failure
        if: steps.rpa.outputs.exit_code != 0
        run: |
          echo "=== RPA SCRIPT FAILED ==="
          echo "Exit code: ${{ steps.rpa.outputs.exit_code }}"
          echo "=== LOG OUTPUT ==="
          cat rpa_output.log
          echo "=== END LOG ==="

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rpa-logs-${{ github.run_number }}
          path: |
            rpa_output.log
            debug_*.png
            downloads/

      - name: RPA Execution Summary
        run: |
          echo "=== RPA EXECUTION SUMMARY ==="
          echo "Exit code: ${{ steps.rpa.outputs.exit_code }}"
          echo "Date/Time: ${{ github.run_started_at }}"
          echo "Commit: ${{ github.sha }}"
          if [ "${{ steps.rpa.outputs.exit_code }}" = "0" ]; then
            echo "Status: ✅ SUCCESS - RPA executed successfully!"
            echo "Check artifacts for downloaded files and logs."
          else
            echo "Status: ❌ FAILED - RPA execution failed!"
            echo "Check logs for error details."
          fi
          echo "================================"