name: Test Supabase Connection

import psycopg2
import os

# Variáveis de ambiente (virão dos Secrets no GitHub Actions)
USER = os.getenv("user")
PASSWORD = os.getenv("password")
HOST = os.getenv("host")
PORT = os.getenv("port")
DBNAME = os.getenv("dbname")

try:
    # Conexão com o banco
    connection = psycopg2.connect(
        user=USER,
        password=PASSWORD,
        host=HOST,
        port=PORT,
        dbname=DBNAME,
        sslmode="require"   # 🔑 necessário no Supabase
    )
    print("✅ Connection successful!")

    # Criação de cursor
    cursor = connection.cursor()

    # Exemplo de query
    cursor.execute("SELECT NOW();")
    result = cursor.fetchone()
    print("🕒 Current Time:", result)

    # Fechar cursor e conexão
    cursor.close()
    connection.close()
    print("🔒 Connection closed.")

except Exception as e:
    print(f"❌ Failed to connect: {e}")
